frequency: 60
two_d_mode: true
publish_tf: true

odom_fream: odom
base_link_frame: base_link
world_frame: odom

transform_time_offset: 0.0
transform_timeout: 0.1

odom0: odom
odom_config: [true, true, false,
              false, false, false,
              false, false, false,
              false, false, false,
              false, false, flase]

odom0_differential: true

imu0: imu/data_filtered
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, true,
              false, false, false]

imu0_differential: false

imu0_linear_acceleration_rejection_threshold: 0.8
imu0_remove_gravitational_acceleration: true
